---
- name: create a general purpose t2.micro server node
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    keyname: admin@mhubig.de
    region: eu-central-1 # Frankfurt
    zone: eu-central-1a
    base_image: ami-b83c0aa5 # Ubuntu 14.04 LTS (HVM)
    instance_type: t2.micro
    swap_device: True
    swap_device_size: 4
    number: False
    group: False

  tasks:

    - fail: >
        msg='Security group is missing! e.g: (--extra-vars group=riak-nodes).'
      when: not group

    - fail: >
        msg='Number of nodes is missing! e.g: (--extra-vars number=3).'
      when: not number

    - name: createing the server node
      local_action:
        module: ec2
        count: '{{ number }}'
        image: '{{ base_image }}'
        instance_type: '{{ instance_type }}'
        key_name: '{{ keyname }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        group: '{{ group }}'
        wait: true

        volumes:
          - device_name: /dev/sda1
            volume_size: 8
            device_type: gp2
            delete_on_termination: true

          - device_name: /dev/xvdf
            volume_size: '{{ swap_device_size }}'
            device_type: gp2
            delete_on_termination: true
            when: '{{ swap_device }} = True'

          - device_name: /dev/xvdg
            volume_size: 20
            device_type: gp2
            delete_on_termination: true

      register: ec2

    - name: Wait while the server is starting by checking the ssh port
      wait_for: >
        state=started host={{ item.public_dns_name }}
        port=22 delay=60 timeout=320
      with_items: ec2.instances

    - name: Show the public ips
      debug: msg={{ item.public_ip }}
      with_items: ec2.instances

