---
- name: be sure ntp is installed
  apt: name=ntp state=present

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp
    - set the time

- name: be sure ntp is running and enabled
  service: name=ntp state=running enabled=yes
